# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=32, unique=True)),
                ('ctime', models.DateTimeField(auto_now_add=True, null=True)),
                ('upime', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'invalid': '请输入用户名'}, help_text='输入用户名', max_length=32, verbose_name='用户名')),
                ('password', models.CharField(error_messages={'invalid': '输入密码'}, help_text='输入密码', max_length=64, verbose_name='密码')),
                ('email', models.EmailField(error_messages={'invalid': '请填写邮箱'}, help_text='填写邮箱', max_length=255, null=True, verbose_name='邮箱')),
                ('other', models.CharField(error_messages={'invalid': '请填写备注'}, help_text='填写备注', max_length=255, null=True, verbose_name='备注')),
                ('user_type_id', models.IntegerField(choices=[(1, '超级用户'), (2, '贵宾用户'), (3, '普通用户')], default=1, help_text='选择用户类型', verbose_name='用户类型')),
                ('user_group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.UserGroup')),
            ],
        ),
    ]
